#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-junit-interface
Version  : 0.11
Release  : 1
URL      : https://github.com/sbt/junit-interface/archive/0.11.tar.gz
Source0  : https://github.com/sbt/junit-interface/archive/0.11.tar.gz
Source1  : https://repo1.maven.org/maven2/com/novocode/junit-interface/0.11/junit-interface-0.11.jar
Source2  : https://repo1.maven.org/maven2/com/novocode/junit-interface/0.11/junit-interface-0.11.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mvn-junit-interface-data = %{version}-%{release}

%description
# JUnit Interface
An implementation of [sbt's test interface](https://github.com/sbt/test-interface) for [JUnit 4](http://junit.org/). This allows you to run JUnit tests from [sbt](http://www.scala-sbt.org/).

%package data
Summary: data components for the mvn-junit-interface package.
Group: Data

%description data
data components for the mvn-junit-interface package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/novocode/junit-interface/0.11
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/novocode/junit-interface/0.11

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/novocode/junit-interface/0.11
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/novocode/junit-interface/0.11


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/novocode/junit-interface/0.11/junit-interface-0.11.jar
/usr/share/java/.m2/repository/com/novocode/junit-interface/0.11/junit-interface-0.11.pom
